# Stage 1: Build the Angular application
FROM node:20 as build
WORKDIR /app
ARG API_URL
COPY package.json package-lock.json ./ 
RUN npm install
COPY . .
RUN sed -i "s|apiUrl: ''|apiUrl: '$API_URL'|" src/environments/environment.ts
RUN npm run build -- --configuration production

# Stage 2: Serve the application from Nginx
FROM nginx:alpine
COPY --from=build /app/dist/360-feedback-portal/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080
